# Default values for go-filecoin-devnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
Image: "devnet-base:fast-devnet"
ProofParamsDir: "/home/ognots/filecoin-proof-parameters"
Bootstrap:
  Replicas: 3
Miner:
  Replicas: 2
Sprinkler:
  CronJobConcurrencyPolicy: Forbid
  Schedule: "*/5 * * * *"
